// UI 확인용 더미 데이터 v2 (7축 태그 + 저장수/조회수 + AI 한줄평)
export const MOCK_KPI = {
  weeklyCount: 312,
  risingCategory: { name: '후드집업', score: 24800 },
  topColor: { name: '차콜', score: 41200 },
  topFit: { name: '오버핏', score: 58900 },
  topBrand: { brand: '더콜디스트모먼트', total_likes: 92100 },
}

const weeks = (() => {
  const out = []
  const today = new Date()
  for (let i = 7; i >= 0; i--) {
    const d = new Date(today)
    d.setDate(d.getDate() - i * 7)
    out.push(d.toISOString().slice(0, 10))
  }
  return out
})()

export const MOCK_SERIES = [
  { category: '후드집업', delta: 38, latestLikes: 24800,
    points: weeks.map((w, i) => ({ week: w, likes: 8000 + i * 2200 + Math.random() * 1500 })) },
  { category: '와이드데님', delta: 22, latestLikes: 19400,
    points: weeks.map((w, i) => ({ week: w, likes: 12000 + i * 900 + Math.random() * 1200 })) },
  { category: '버뮤다', delta: 55, latestLikes: 14200,
    points: weeks.map((w, i) => ({ week: w, likes: 3000 + i * 1500 + Math.random() * 800 })) },
  { category: '피그먼트티', delta: -18, latestLikes: 9800,
    points: weeks.map((w, i) => ({ week: w, likes: 18000 - i * 1100 + Math.random() * 900 })) },
  { category: '맨투맨', delta: 4, latestLikes: 13100,
    points: weeks.map((w, i) => ({ week: w, likes: 11000 + i * 250 + Math.random() * 700 })) },
  { category: '셔켓', delta: 12, latestLikes: 7600,
    points: weeks.map((w, i) => ({ week: w, likes: 4500 + i * 400 + Math.random() * 600 })) },
]

export const MOCK_HOT_ITEMS = [
  {
    product_id: 1, brand: 'THECOLDESTMOMENT',
    product_name: 'TCM Heavy Cotton Zip-up Hoodie',
    image_url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600',
    product_url: '#', price: 89000,
    like_count: 24800, save_count: 8200, view_count: 142000, likes_delta: 4200,
    vlvd_category: '후드집업', fit: '오버핏',
    mood: ['스트릿', '미니멀'],
    primary_color: '차콜',
    color_palette: ['차콜', '블랙'],
    detail_tags: ['피그먼트', '엠브로이더리'],
    silhouette: '박시', material: '헤비코튼',
    graphic: ['스몰로고'],
    season: 'FW', gender: 'U', confidence: 0.92,
    ai_notes: '헤비웨이트 원단과 차콜 톤이 만들어내는 단정한 스트릿. 26FW 메인 후보감.',
  },
  {
    product_id: 2, brand: 'CODEGRAPHY',
    product_name: '시그니처 와이드 데님 팬츠',
    image_url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600',
    product_url: '#', price: 79000,
    like_count: 19400, save_count: 6100, view_count: 98000, likes_delta: 3800,
    vlvd_category: '데님', fit: '와이드',
    mood: ['스트릿', '빈티지'],
    primary_color: '인디고',
    color_palette: ['인디고', '미디엄블루'],
    detail_tags: ['워싱', '데미지'],
    silhouette: '스트레이트', material: '데님',
    graphic: ['무지'],
    season: 'ALL', gender: 'U', confidence: 0.88,
    ai_notes: '와이드 실루엣 + 미세한 데미지 워싱. 다음 시즌 데님 라인업 벤치마크.',
  },
  {
    product_id: 3, brand: 'MARITHE',
    product_name: 'Classic Logo Sweatshirt',
    image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600',
    product_url: '#', price: 69000,
    like_count: 18200, save_count: 5800, view_count: 87000, likes_delta: 3100,
    vlvd_category: '맨투맨', fit: '오버핏',
    mood: ['스트릿', '스포티'],
    primary_color: '크림',
    color_palette: ['크림', '브라운'],
    detail_tags: ['나염', '레터링'],
    silhouette: '박시', material: '맨투맨원단',
    graphic: ['빅로고', '레터링'],
    season: 'FW', gender: 'U', confidence: 0.90,
    ai_notes: '큰 로고 프린트가 시선 잡는 캐주얼 베이직. 크림 컬러가 차별 포인트.',
  },
  {
    product_id: 4, brand: 'INSILENCE',
    product_name: 'Pigment Washed Cotton Bermuda',
    image_url: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600',
    product_url: '#', price: 65000,
    like_count: 14200, save_count: 4200, view_count: 71000, likes_delta: 2900,
    vlvd_category: '버뮤다', fit: '레귤러',
    mood: ['빈티지', '워크웨어'],
    primary_color: '카키',
    color_palette: ['카키', '머드'],
    detail_tags: ['피그먼트', '워싱', '빈티지가공'],
    silhouette: '스트레이트', material: '코튼',
    graphic: ['무지'],
    season: 'SS', gender: 'M', confidence: 0.87,
    ai_notes: '피그먼트 톤이 빈티지 무드를 살린 버뮤다. 27SS 출고 검토.',
  },
  {
    product_id: 5, brand: 'NICEGHOST',
    product_name: 'Heavy Cotton Hooded Zip-up Black',
    image_url: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600',
    product_url: '#', price: 95000,
    like_count: 16800, save_count: 5400, view_count: 92000, likes_delta: 2700,
    vlvd_category: '후드집업', fit: '오버핏',
    mood: ['미니멀', '스트릿'],
    primary_color: '블랙',
    color_palette: ['블랙'],
    detail_tags: ['엠브로이더리'],
    silhouette: '박시', material: '헤비코튼',
    graphic: ['스몰로고'],
    season: 'FW', gender: 'U', confidence: 0.93,
    ai_notes: '블랙 헤비코튼 후드집업의 정석. 컬러 다양화 시 26FW 메인 추천.',
  },
  {
    product_id: 6, brand: 'PARTIMENTO',
    product_name: '오리지널 카고 와이드 팬츠',
    image_url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600',
    product_url: '#', price: 85000,
    like_count: 12300, save_count: 3900, view_count: 64000, likes_delta: 2300,
    vlvd_category: '카고팬츠', fit: '와이드',
    mood: ['워크웨어', '아메카지'],
    primary_color: '베이지',
    color_palette: ['베이지', '카키'],
    detail_tags: ['패치', '드로스트링'],
    silhouette: '스트레이트', material: '코튼',
    graphic: ['무지'],
    season: 'ALL', gender: 'M', confidence: 0.89,
    ai_notes: '와이드 카고는 26SS-FW 사계절 코어. 디테일 카피 후보.',
  },
  {
    product_id: 7, brand: 'VIVASTUDIO',
    product_name: '시그니처 후드 풀오버 멜란지 그레이',
    image_url: 'https://images.unsplash.com/photo-1572495641004-28421ae29ed4?w=600',
    product_url: '#', price: 75000,
    like_count: 11900, save_count: 3700, view_count: 58000, likes_delta: 2100,
    vlvd_category: '후드', fit: '오버핏',
    mood: ['미니멀', '스포티'],
    primary_color: '멜란지그레이',
    color_palette: ['멜란지그레이', '차콜'],
    detail_tags: ['엠브로이더리'],
    silhouette: '박시', material: '맨투맨원단',
    graphic: ['스몰로고'],
    season: 'FW', gender: 'U', confidence: 0.91,
    ai_notes: '멜란지 그레이가 단순한 후드를 고급스럽게 만든다. 컬러 학습 케이스.',
  },
  {
    product_id: 8, brand: 'COVERNAT',
    product_name: 'A-1 Deck Jacket Olive',
    image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600',
    product_url: '#', price: 159000,
    like_count: 9800, save_count: 3100, view_count: 47000, likes_delta: 1900,
    vlvd_category: '워크자켓', fit: '레귤러',
    mood: ['워크웨어', '아메카지'],
    primary_color: '올리브',
    color_palette: ['올리브', '카키'],
    detail_tags: ['패치', '버튼다운'],
    silhouette: '박시', material: '캔버스',
    graphic: ['패치'],
    season: '간절기', gender: 'M', confidence: 0.86,
    ai_notes: '데크 자켓의 클래식 실루엣. 캔버스 소재 검토할 만한 레퍼런스.',
  },
]
